feat(actions): Run on manual dispatch

diff --git a/.github/workflows/update-redis-keys.yml b/.github/workflows/update-redis-keys.yml
--- a/.github/workflows/update-redis-keys.yml
+++ b/.github/workflows/update-redis-keys.yml
@@ -1,14 +1,12 @@
-name: Update Redis Keys on PR Merge to Main
+name: Update SDK Redis Keys
 
 on:
-  push:
-    branches:
-      - feat/actions-delete-redis-keys
-  pull_request:
-    types:
-      - closed
-    branches:
-      - main
+  workflow_dispatch:
+    inputs:
+        target:
+          description: 'Deployment target (dev, stage, or prod)'
+          required: true
+          default: 'dev'
 
 jobs:
   update-redis-keys:
@@ -21,6 +19,13 @@ jobs:
       id-token: write
 
     steps:
+      - name: Validate target
+        if: ${{ !contains('dev,stage,prod', github.event.inputs.target) }}
+        run: |
+          echo "❌ Invalid target: ${{ github.event.inputs.target }}"
+          echo "    Allowed values are: dev, stage, prod"
+          exit 1
+
       - name: "Authenticate to Google Cloud"
         uses: "google-github-actions/auth@v2"
         with:
@@ -39,9 +44,10 @@ jobs:
 
       - name: Set up SSH SOCKS proxy
         env:
-          REDIS_HOST: 10.128.0.62
+          REDIS_HOST: ${{ github.event.inputs.target == 'stage' ? '10.128.0.62' : github.event.inputs.target == 'prod' ? '10.128.15.192' : '10.128.0.114' }}
+          PROXY_CLUSTER: ${{ github.event.inputs.target == 'stage' ? 'proxy-stage-cluster' : github.event.inputs.target == 'prod' ? 'proxy-prod-cluster' : 'proxy-dev-cluster' }}
         run: |
-          gcloud beta compute ssh proxy-stage-cluster \
+          gcloud beta compute ssh $PROXY_CLUSTER \
             --project x-cycling-414419 \
             --zone us-central1-a \
             --tunnel-through-iap \
